# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Website generation

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  workflow_dispatch:  # For manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare git
        run: |
          git config --global user.name "${{ secrets.BOT_GH_NAME}}"
          git config --global user.email "${{ secrets.BOT_GH_EMAIL}}"

      - name: Apply netrc creds with direct input again
        uses: little-core-labs/netrc-creds@master
        with:
          machine: github.com
          login: ${{ secrets.BOT_GH_NAME}}
          password: ${{ secrets.BOT_TOKEN}}

      #
      # COMPILATION
      #

      - uses: actions/setup-node@v3
        with:
          node-version: 'current'

      - name: Install dependencies
        run: yarn install

      - name: Build website
        run: yarn docusaurus build

      - name: Deploy website
        run: yarn docusaurus deploy
